stages:
  - build
  - test

variables:
  BUNDLE_PATH: vendor/bundle

default:
  tags:
    - tf-gitlab-runner

build:
  stage: build
  image:
    name: ruby:3.4.2-slim
    pull_policy: if-not-present

  before_script:
    - |
      apt update && apt install -y \
        build-essential \
        libssl-dev \
        libyaml-dev
    - bundle config set --local path $BUNDLE_PATH
  script:
    - bundle install

  artifacts:
    when: on_success
    name: "$CI_COMMIT_REF_NAME-gems"
    expire_in: 1 hour
    paths:
      - ./vendor/*

rubocop:
  stage: test
  image:
    name: ruby:3.4.2-slim
    pull_policy: if-not-present

  needs: [build]

  script:
    - bundle exec rubocop --format progress

rspec:
  stage: test
  image:
    name: ruby:3.4.2-slim
    pull_policy: if-not-present

  services:
    - name: alpine/sqlite:3.49.2
      pull_policy: if-not-present

  needs: [build]

  before_script:
    - bundle config set --local path $BUNDLE_PATH
    - bundle exec rails db:prepare
  script:
    - bundle exec rspec

  artifacts:
    when: on_success
    name: "$CI_COMMIT_REF_NAME"
    expire_in: 1 hour
    paths:
      - ./coverage/*

coverage:
  stage: test
  image:
    name: ruby:3.4.2-slim
    pull_policy: if-not-present

  needs: [rspec]

  before_script:
    - apt update && apt install -y jq
  script:
    - COVERAGE="$(cat ./coverage/.last_run.json | jq .result.line)"
    - |
      if [[ "$(echo "$COVERAGE <= 100.0" | bc)" = 1 ]]; then
        echo "Quota coverage not reached!"
      else
        echo "Quota coverage reached!";
      fi
